### ISSUE TITLE
EGRET-T model not working for training.

### ISSUE THREAD

**Issue by pedrojuanbj** [CSML-IIT-UCL/franken#12]
Hello, 

I downloaded the EGRET-1T model and I wanted to use it for training, but it keeps failing. I tried the same training with MACE-OFF24 and it works just fine. I am unsure what could be the issue here. 

This exact model: https://github.com/rowansci/egret-public/blob/master/compiled_models/EGRET_1T.model

This is the error, it seems to happen when coevs+coeffs:
```
2025-06-11 21:11:34.976 ERROR (rank 0): Error encountered in autotune. Exiting.
Traceback (most recent call last):
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/franken/autotune/script.py", line 332, in autotune
    run_autotune(
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/franken/autotune/script.py", line 169, in run_autotune
    logs, weights = trainer.fit(model, solver_param_grid)
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/franken/trainers/rf_cuda_lowmem.py", line 139, in fit
    self._compute_covs_and_coeffs(model, self.train_dataloader)
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/franken/trainers/rf_cuda_lowmem.py", line 386, in _compute_covs_and_coeffs
    forces_fmap, energy_fmap = model.grad_feature_map(data)
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/franken/rf/model.py", line 213, in grad_feature_map
    return self._grad_fmap_jacfn(data.atom_pos, data)
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/franken/utils/jac.py", line 48, in wrapper_fn
    results = vmap(push_jvp, randomness=randomness, chunk_size=chunk_size)(basis)
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/torch/_functorch/apis.py", line 202, in wrapped
    return vmap_impl(
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/torch/_functorch/vmap.py", line 323, in vmap_impl
    return _chunked_vmap(
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/torch/_functorch/vmap.py", line 435, in _chunked_vmap
    _flat_vmap(
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/torch/_functorch/vmap.py", line 484, in _flat_vmap
    batched_outputs = func(*batched_inputs, **kwargs)
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/franken/utils/jac.py", line 37, in push_jvp
    output = _jvp_with_argnums(
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/torch/_functorch/eager_transforms.py", line 1101, in _jvp_with_argnums
    result_duals = func(*duals)
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/franken/rf/model.py", line 189, in _feature_map_aux
    random_features = self.feature_map(data)
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/franken/rf/model.py", line 175, in feature_map
    gnn_descriptors = self.gnn.descriptors(data)
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/franken/backbones/wrappers/mace_wrap.py", line 81, in descriptors
    edge_attrs = self.spherical_harmonics(vectors)
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
```

**Comment by pedrojuanbj** [comment]
Hi I used this exact python API to run it:

```
import json
import sys

from franken.autotune import autotune
from franken.config import MaceBackboneConfig, GaussianRFConfig, DatasetConfig, SolverConfig, HPSearchConfig, AutotuneConfig, MultiscaleGaussianRFConfig
import os
os.environ["SLURM_NTASKS_PER_NODE"] = "1"

args = sys.argv 
train = args[1]
test = args[2]
backbone = args[3]
n_features = args[4]


gnn_config = MaceBackboneConfig(
    path_or_id=backbone,
    interaction_block=2,
)
dataset_cfg = DatasetConfig(name="MALD", train_path=train, val_path=test)

rf_config = MultiscaleGaussianRFConfig(
    num_random_features=int(n_features),
    length_scale_high=50,
    length_scale_low=10,
    length_scale_num=25,
    rng_seed=42,
)

solver_cfg = SolverConfig(
    l2_penalty=HPSearchConfig(start=-10, stop=0, num=25, scale='log'),  # equivalent of numpy.logspace
    force_weight=HPSearchConfig(start=0.1, stop=0.99, num=25, scale='linear'),  # equivalent of numpy.linspace
)

dirr = train.split('/')[-1].split('.')[0]
bb = backbone.split('/')[-1].split('.')[0]
print(dirr)


autotune_cfg = AutotuneConfig(
    dataset=dataset_cfg,
    solver=solver_cfg,
    backbone=gnn_config,
    rfs=rf_config,
    seed=42,
    jac_chunk_size=1,
    run_dir=f"./MALD_franken_{n_features}_{bb}_{dirr}",
)

run_path = autotune(autotune_cfg)
```
Called it with:
`python3 run_franken_script.py datasets/train_1_b3lyp.xyz datasets/train_2_b3lyp.xyz ../../../ckpts/EGRET_1T.model  16384 > train1_test2.out `

I have the path in case you want to check on Franklin, it should be accessible.

**Comment by Giodiro** [comment]
Thanks! Could you try the version on the main branch? It should be fixed for real

**Comment by pedrojuanbj** [comment]
> Thanks! Could you try the version on the main branch? It should be fixed for real

Hi @Giodiro, I tried installing from the main branch, but the error is still there when training :( .  

I'll try not using the API using the CLI instead.

**Comment by Giodiro** [comment]
Yeah no problem! I also noticed this CLI thing and it turned out to be bigger than expected, will let you know as soon as I get it to work :)

**Comment by pedrojuanbj** [comment]
Is the EGRET-T1 model working for you then? At least on the API? For me it didnt so far.

**Comment by Giodiro** [comment]
No! I had a simple test that worked, but then it did not work on water.
I think I could have it fixed now (on main branch)!
My test command is
```
PYTHONPATH='.' python franken/autotune/script.py \
    --dataset-name="water" \
    --max-train-samples=8 \
    --l2-penalty="(-10, -5, 5, log)" \
    --force-weight="(0.01, 0.99, 5, linear)" \
    --seed=42 \
    --jac-chunk-size=16 \
    --run-dir="./results" \
    --backbone=mace \
    --mace.path-or-id="Egret-1t" \
    --mace.interaction-block 2 \
    --rf=gaussian \
    --gaussian.num-rf=512 \
    --gaussian.length-scale="[10.0, 15.0]"
```
which seems to work! Let me know if it's fixed for you!

**Comment by Giodiro** [comment]
I assume it's fixed, @pedrojuanbj please re-open if it's not.

**Comment by pedrojuanbj** [comment]
Hi @Giodiro  I cannot reopen, I don't have permissions.  Sorry it took a bit to get back to this. 

I tried your exact example and it works as you wrote it with EGRET, but when you specify the dataset it creates another error which ends up being: 
FileNotFoundError: [Errno 2] No such file or directory: 'None'

Traceback basically is: 
Traceback (most recent call last):
```
  File "/work/pbuigues/pedro/MALD/franken_trainings/franken/franken/autotune/script.py", line 313, in autotune
    loaders = init_loaders(
  File "/work/pbuigues/pedro/MALD/franken_trainings/franken/franken/autotune/script.py", line 71, in init_loaders
    dset = BaseAtomsDataset.from_path(
  File "/work/pbuigues/pedro/MALD/franken_trainings/franken/franken/data/base.py", line 305, in from_path
    return MACEAtomsDataset(
  File "/work/pbuigues/pedro/MALD/franken_trainings/franken/franken/data/mace.py", line 61, in __init__
    super().__init__(data_path, split, num_random_subsamples, subsample_rng)
  File "/work/pbuigues/pedro/MALD/franken_trainings/franken/franken/data/base.py", line 142, in __init__
    read_ase_atoms = ase.io.read(self.data_path, index=":")
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/ase/io/formats.py", line 808, in read
    format = format or filetype(filename, read=isinstance(filename, str))
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/ase/io/formats.py", line 983, in filetype
    fd = open_with_compression(filename, 'rb')
  File "/projects/mlcompchem/HBQ/fresh_env_franken_py3.10/lib/python3.10/site-packages/ase/io/formats.py", line 612, in open_with_compression
    return open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'None'
```
I believe the default gets passed as None if not specified in the training when you specify a custom dataset. 

The CLI only goes through if I specify all three (train/test/val) datasets. Otherwise the error above happens.

**Comment by pedrojuanbj** [comment]
By the way, this error also happens when using the API still. 

Funny thing is, if I change to use the water dataset from registry, I get first an error about not fitting into memory, If I swap to A100 that error goes away but the "RuntimeError: Cannot access data pointer of Tensor that doesn't have storage" comes back.

**Comment by pedrojuanbj** [comment]
> I'm not sure I understand, in your first message the water dataset is working and in the last message it is not any more?

Apologies, the CLI error was regarding specifying datasets. Apart from that, even when running your water dataset the "cannot access data" error comes back.  I cannot try again now Franklin is down, but I'll move stuff on Leonardo and do some tests soon. I'll prepare a folder for you.

**Comment by Giodiro** [comment]
But it worked at some time right?
You wrote: "I tried your exact example and it works as you wrote it with EGRET,"

**Comment by Giodiro** [comment]
Hi @pedrojuanbj , do you have any updates on this?
It's unclear to me if it's fixed or not :)
